# Custom Language File for Launcher Customizer

[ejs.app]
title = "LaBulle MC"

[ejs.landing]
mediaGitHubURL = "https://github.com/jlSebeleuuu/LaBulleMC-Launcher"
mediaXURL = "#"
mediaInstagramURL = "https://www.instagram.com/sebb.lrn/"
mediaDiscordURL = "https://discord.gg/cjDgNSAQRA"

[ejs.settings]
sourceGithubLink = "https://github.com/jlSebeleuuu/LaBulleMC-Launcher"
supportLink = "https://github.com/jlSebeleuuu/LaBulleMC-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur LaBulle MC"
welcomeDescription = "Un serveur survie moddé, imaginé et développé par la communauté, pour la communauté."
welcomeDescCTA = "Il ne vous reste plus que quelques clics pour rejoindre l’aventure."

